server:
  port: 8880

spring:
  application:
    name: cloud-api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      # 包含了所有服务、路径和过滤器的完整路由规则
      routes:
        - id: user_service_route # 名字可以自己取
          uri: lb://cloud-user-service # 指向用户服务
          predicates:
            - Path=/api/user/** # 匹配所有 /api/user/ 开头的请求
          filters:
            - StripPrefix=2 # 去掉 /api/user

        - id: article_service_route # 名字可以自己取
          uri: lb://article-service # 指向文章服务
          predicates:
            - Path=/api/article/** # 匹配所有 /api/article/ 开头的请求
          filters:
            - StripPrefix=2 # 去掉 /api/article

    # 解决503问题的配置
    loadbalancer:
      ribbon:
        enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/

# 暴露诊断端点的配置
management:
  endpoints:
    web:
      exposure:
        include: "*"
